### ISSUE TITLE
RuntimeError: implement_array_function method already has a docstring

### ISSUE THREAD

**Issue by VahedCivil** [Almenon/AREPL-vscode#422] opened 2022-01-07 18:44 UTC
Hi
I take this error during using **AREPL for python** :

Traceback (most recent call last):
  line 1, in <module>
  File "D:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 138, in <module>
    from . import cbook, rcsetup
  File "D:\ProgramData\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 31, in <module>
    import numpy as np
  File "D:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "D:\ProgramData\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "D:\ProgramData\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "D:\ProgramData\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 47, in <module>
    """)
RuntimeError: implement_array_function method already has a docstring

but I run it in terminal without any problem. This is my code:

`
import matplotlib.pyplot as plt
import json

fileName = r"Test codes\InternalForces\BLSPSW-11-10-T4--InternalForce.json"
with open(fileName, "r") as read_file:
    data = json.load(read_file)

print(len(data))

def conditions(r): return r['DriftValue'] > 0 and \
    r['ForceName'] == "Bending Moment" and \
    r['ElementName'] == "Top Beam"

filerData = list(filter(conditions, data))
print(len(filerData))

for r in filerData:
    plt.plot(r['x'], r['y'], label=r['DriftName'])

lastData = filerData[-1]
plt.xlabel(lastData['xLable'])
plt.ylabel(lastData['yLable'])
plt.title(lastData['ModelName'] + ', ' + lastData['ElementName'])

plt.legend()
plt.show()
`
How can I solve it?
Thanks.

**Comment by Almenon** [comment] 2022-01-08 17:49
duplicate of https://github.com/Almenon/AREPL-vscode/issues/386 - you can fix this by upgrading numpy to version 1.19

**Closed by Almenon** 2022-01-08 17:49 UTC

**Comment by VahedCivil** [comment] 2022-01-08 21:14
Thanks

**Comment by Almenon** [comment] 2022-05-15 01:45
Hi @VahedCivil, would you be open to a short customer interview on how you're using/used AREPL?
