### ISSUE TITLE
Memory leak with `input()`

### ISSUE THREAD

**Issue by goyalyashpal** [Almenon/AREPL-vscode#444] opened 2023-04-05 14:31 UTC
### Describe the bug
Power/memory consumption skyrockets when there's a, say, naked `input()`
Naked means that the ways mentioned at wiki at [Using AREPL with input] aren't used.

[Using AREPL with input]: https://github.com/Almenon/AREPL-vscode/wiki/Using-AREPL-with-input

### To Reproduce
1. Use `input()` in your python code
2. Run AREPL
3. Wait for some time (2-3 minutes) to see the observed behaviour

#### Observed behaviour
- AREPL keeps on running infinitely, 
- the output logs in AREPL panel keep on increasing
- PC starts lagging after some time - opening Task Manager reveals that VSCodium (13) is using 1.6k to 2.2k MB in memory
- ... Now close the AREPL pannel, and see the VSCodium (7to10) is using only about 350 MB memory

#### Expected behavior
- Resource usage shouldn't skyrocket

<details>
<summary>
<h3>Screenshots</h3>
<br/>If applicable, add screenshots to help explain your problem.
</summary>

<br/>

<img src="https://user-images.githubusercontent.com/19423063/230110930-6d12b24d-274e-492b-bf2a-758bddd124bd.png" width=500px/>

<img src="https://user-images.githubusercontent.com/19423063/230110956-3b5e8c84-979a-4e94-b9b1-ee3a131bbc99.png" width=750px/>

</details>

### Other Information 
(please complete the following information):

 - OS: Windows 10
 - Python Version: Python 3.11.2
 - VS Codium: 1.77.0
 - AREPL: 2.0.5

**Comment by goyalyashpal** [comment] 2023-04-05 14:38
What more, it even prevents AREPL from recovering and responding to a change in the source file - like say i try to make it work via the `standard_input` variable way...

It essentially is like a memory leak - just that one such where it doesn't lead to crash

**Comment by goyalyashpal** [comment] 2023-04-05 14:46
Just a tip for anyone facing this problem:

1. close the arepl panel immediately
2. add the `standard_input =` or whatever method given at that [wiki Using AREPL with input](https://github.com/Almenon/AREPL-vscode/wiki/Using-AREPL-with-input) at the top of the file (think: global scope)
3. re-click the arepl button
4. see if arepl recognises these hardcoded standard_inputs, if not, then repeat from step 1

**Comment by Almenon** [comment] 2023-04-05 15:46
Please copy and paste the full block of code here needed to reproduce the problem

**Comment by goyalyashpal** [comment] 2023-04-05 15:47
2 more things:
- owing to mention at https://github.com/Almenon/AREPL-vscode/issues/6#issuecomment-448086008 , i think this issue belongs to repo: Almenon/AREPL-backend
- the wording shown on error should be improved to contain link the wiki

**Comment by Almenon** [comment] 2023-04-05 15:53
Also without looking at your code I'm guessing you have a infinite loop. When you have a infinite loop the process is stuck evaluating your code so you need to restart AREPL.

https://github.com/Almenon/AREPL-vscode/issues/439 would fix AREPL such that it doesn't get stuck when it encounters a infinite loop.

**Comment by goyalyashpal** [comment] 2023-04-05 16:00
> Please copy and paste the full block of code here needed to reproduce the problem

ahw, got it. the input was put in a while loop for input validation.

> I'm guessing you have a infinite loop in your code

yep, i am trying to create a minimal isolated code. but the computer is lagging alot.

**Comment by goyalyashpal** [comment] 2023-04-05 16:31
Minimal (slightly non minimal) isolated code causing problems

```python
# standard_input = 'hi'

num = 0
# Get a positive integer, re-prompt if uncompliant
while True:
    try:
        num = int(input("Enter number: "))
    except ValueError:
        pass
    else:
        if num > 0:
            break

print(num)
```

**Comment by Almenon** [comment] 2023-04-07 05:19
Yep, that's a infinite loop alright. I'm closing this as a duplicate of #439 , but let me know if you run into other problems. I generally work on AREPL whenever I get a new review in the VSCode Marketplace, which happens around once a month, so #439 might be completed in a few months?

On a sidenote, I'm interested in how you're using AREPL. Are you open to a short call with me in about a month or so?

**Closed by Almenon** 2023-04-07 05:19 UTC

**Comment by goyalyashpal** [comment] 2023-04-09 15:29
> I'm interested in how you're using AREPL. Are you open to a short call with me in about a month or so?

yeah, sure. but how?

**Comment by Almenon** [comment] 2023-04-09 17:49
We could do zoom. Do you have an email you feel comfortable posting here? If not you can email me at almenon214 
 at g mail

**Comment by goyalyashpal** [comment] 2023-04-09 17:56
if you can share your telegram id, that'd work well with me ?

**Comment by Almenon** [comment] 2023-04-09 18:43
@goyalyashpal 6173 9  42520

**Comment by goyalyashpal** [comment] 2023-04-10 02:42
i think one digit is missing?

https://t.me/+6173942520
https://t.me/6173942520

It says, there's no telegram account with this phone number

**Comment by Almenon** [comment] 2023-04-10 02:51
That's not a phone number, that's a telegram user id

**Comment by goyalyashpal** [comment] 2023-04-10 04:53
yep, i tried, the second link is for id...

ohhh, sorry, my mistake. i meant telegram username, not telegram id. 

i dont know how to initiate a chat using tg-id

**Comment by Almenon** [comment] 2023-04-13 15:43
My telegram username is Calsem
