### ISSUE TITLE
Interfering with AutoSave default vscode feature

### ISSUE THREAD

**Issue by chiboreache** [Almenon/AREPL-vscode#179] opened 2019-02-10 14:25 UTC
Every time when it goes to autosave temporary created AREPL file (*Untitled-1* for example) I have the following message in my **OUTPUT** section:

```
[Error - 5:11:16 PM] Request textDocument/completion failed.
  Message: unknown document
  Code: -32000 
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(Uri documentUri, Boolean throwIfMissing)
   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(TextDocumentIdentifier document, Nullable`1 expectedVersion, ProjectEntry& entry, PythonAst& tree)
   at Microsoft.Python.LanguageServer.Implementation.Server.Completion(CompletionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Completion(JToken token, CancellationToken cancellationToken)
```

which is pop-upping every 1000ms, extremely annoying `~_~`

But I am not sure about autosave, it's just my assumption ;)

**Comment by Almenon** [comment] 2019-02-10 16:29
what is a "OUTPUT" section? I'm not sure what screen you're referring to there. 

As for the output you posted, it appears to be some sort of error with microsoft's python extension.

**Comment by Almenon** [comment] 2019-02-10 16:29
If it's not too much work, can you take a image of the error?  

I suggest using sharex, but you're welcome to use whatever

https://getsharex.com/

**Comment by chiboreache** [comment] 2019-02-11 09:50
Sure

![screenshot_20190211_124754](https://user-images.githubusercontent.com/16459251/52555706-843ad480-2dfb-11e9-9c85-977386bbc0dc.png)


btw you can just drag'n'drop images into github write-text-area from default KDE print-screen tool ;)

**Comment by Almenon** [comment] 2019-02-16 04:58
Ah, you're looking at python output. In that case it's an error with the Python extension - can you open a issue in their repo please? https://github.com/Microsoft/vscode-python/issues/new

Also I'm not able to reproduce with arepl version 1.0.8, vscode version 1.31.1, and python version 2019.1.0  - Do you have the latest versions of all installed?

As a workaround you can select a different output to view or not be on the output tab. (although I'm guessing you open for a particular reason)

**Comment by Almenon** [comment] 2019-02-16 04:59
Closing because not a error with arepl - feel free to continue disucssion however.

**Closed by Almenon** 2019-02-16 04:59 UTC
