### ISSUE TITLE
Stops working with end parameter from print method

### ISSUE THREAD

**Issue by semperor** [Almenon/AREPL-vscode#327] opened 2020-04-15 22:01 UTC
**Describe the bug**
arepl seems to stop working with some code from the python tutorial (last example at the end of https://docs.python.org/3/tutorial/introduction.html).

```python
a, b = 0, 1
while a < 1000:
    print(a, end=',')
    a, b = b, a+b
```

Everytime I get the following weird output. Sometimes I got also an syntax error.
> **Print Output:**
0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,6q3co7{"userError": "", "userVariables": "{\"a\": 1597, \"b\": 2584}", "execTime": 0.0009980201721191406, "totalPyTime": 0.0030028820037841797, "internalError": null, "caller": "<module>", "lineno": -1, "done": true, "count": -1}

**To Reproduce**
1. Open empty py file
2. Enter the code from above
3. Make a change (like adding a space)

**Other Information**
 - OS: Windows 10
 - Python Version: 3.8.2

**Comment by Almenon** [comment] 2020-04-17 04:29
I won't be able to fix it today so just letting you know that this is a bug, thanks for reporting it. I'm currently investigating it. My notes so far below.

1. **Try to reproduce**

I was able to reproduce your error

2. **Narrow down the problem**

I was able to reproduce your error with just `print('hi', end=',')`

3. **Compare to working example**

`print('hi')` work as expected.

This indicates that the error is due to the end argument of print.

4. **investigate source code**

5. **debug**

In the `handleResult` method in the backend the result that came in was the following:

```
"hi,6q3co7{"userError": "", "userVariables": "{}", "execTime": 0.0009889602661132812, "totalPyTime": 0.001992940902709961, "internalError": null, "caller": "<module>", "lineno": -1, "done": true, "count": -1}"
```

I use 6q3co7 as a identifier to signal the start of a result, rather than simply a print from the user.  But we are getting the print output first "hi," - that should not happen. What I'm guessing is that print doesn't flush the output until it gets a newline.

6. **Test hypothesis**

In arepl I ran the following:
```python
print('ha',end='')
from time import sleep
sleep(5)
print('yo')
```

What I would expect as a normal user of the app is "ha" would print immediately, followed by a 5 second pause, and then 'yo'. Instead nothing happened for 5 seconds, and then it printed all at once. This leads me to believe that my hypothesis is correct - print doesn't flush until it has a newline.

7. **research**

According to https://realpython.com/python-print/ there are 3 buffering modes:
* unbuffered - output is flushed immediately
* line buffered - output is flushed every newline
* size buffered - output is flushed when it hits a certain size

The website says that Standard output is both line buffered and size buffered. But I launched python in **unbuffered** mode, so why am I having this issue? 🤔 

After some experimentation with buffered and unbuffered mode with vanilla python compared to arepl, I made two unfortunate discoveries. 
1. I shouldn't have ran python with -u for arepl. It's unnecessary.
2. The problem is even deeper than I thought - I think python-shell is buffering the output and that is causing the problem.

**Comment by Almenon** [comment] 2020-04-17 04:32
Note as a workaround for now you can make sure that end has a newline. For example:

```python
a, b = 0, 1
while a < 1000:
    print(a, end=',\n', flush=True)
    a, b = b, a+b
```

**Comment by Almenon** [comment] 2020-04-17 04:33
Or you can simply not bother with end:
```python
a, b = 0, 1
while a < 1000:
    print(str(a)+',')
    a, b = b, a+b
```

**Comment by Almenon** [comment] 2020-05-03 16:57
Fixed in backend but I still need to test change in frontend and do a new release

**Closed** 2020-05-23 23:53 UTC
Labels: bug

**Comment by Almenon** [comment] 2020-05-24 17:10
I just released AREPL 1.0.24!

print with end parameter should work now. @semperor can you verify please?

Sorry for the delay, to fix this I had to split variable results and print results into different pipes and I ran into a whole bunch of problems.
