### ISSUE TITLE
Arepl errors out with Numpy usage

### ISSUE THREAD

**Issue by deltagammavega** [Almenon/AREPL-vscode#409] opened 2021-07-10 14:41 UTC
**Describe the bug**

While using Numpy, Arepl crashes, going from an exception (please see below) to a message (please see below) saying that it has encountered an issue. 

The same code ran in a Jupyter notebook without any issues.

**To Reproduce**

1. Used the following program:

import numpy as np
import pandas as pd

first=np.arange(0, 10,2)
second=np.arange(10, 20, 2)
third=np.arange(20, 30, 2)

my_list=[]

for i, j, k in zip(first, second, third):
    my_list.append((i, j, k))
    
print(my_list)

**Expected behavior**
1) Arepl shouldn't crash.
2) Should give the following output: [(0, 10, 20), (2, 12, 22), (4, 14, 24), (6, 16, 26), (8, 18, 28)]

**Screenshots**

1) First error thrown.
Print Output:
Exception ignored in: <function BaseEventLoop.__del__ at 0x12a2d7c10>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 683, in __del__
    self.close()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 58, in close
    super().close()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 92, in close
    self._close_self_pipe()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 99, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 284, in _remove_reader
    self._selector.unregister(fd)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 539, in unregister
    self._selector.control([kev], 0, 0)
TypeError: changelist must be an iterable of select.kevent objects
[(0, 10, 20), (2, 12, 22), (4, 14, 24), (6, 16, 26), (8, 18, 28)]

2) Second Error Thrown:

Sorry, AREPL has ran into an error

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 261, in _add_reader
    key = self._selector.get_key(fd)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 193, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '6 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lahore/.vscode/extensions/almenon.arepl-2.0.2/node_modules/arepl-backend/python/arepl_python_evaluator.py", line 298, in main
    return_info = exec_input(execArgs)
  File "/Users/lahore/.vscode/extensions/almenon.arepl-2.0.2/node_modules/arepl-backend/python/arepl_python_evaluator.py", line 234, in exec_input
    asyncio.set_event_loop(asyncio.new_event_loop())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 761, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 61, in __init__
    self._make_self_pipe()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 112, in _make_self_pipe
    self._add_reader(self._ssock.fileno(), self._read_from_self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 263, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 523, in register
    self._selector.control([kev], 0, 0)
TypeError: changelist must be an iterable of select.kevent objects

Print Output:
Exception ignored in: <function BaseEventLoop.__del__ at 0x12a2d7c10>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 683, in __del__
    self.close()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/unix_events.py", line 60, in close
    for sig in list(self._signal_handlers):
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_signal_handlers'

**Other Information (please complete the following information):**
 - OS: MacOS, High Sierra, 10.13.6
 - Python Version 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:06:10) 
[Clang 6.0 (clang-600.0.57)]

**Additional context**

**Comment by Almenon** [comment] 2021-07-12 20:15
This is a bug, sorry. Duplicate of https://github.com/Almenon/AREPL-vscode/issues/387 - closing

**Closed by Almenon** 2021-07-12 20:15 UTC

**Comment by Almenon** [comment] 2021-07-12 20:16
Until I fix it on my end you can fix it on your end by following https://github.com/Almenon/AREPL-vscode/issues/387#issuecomment-828873322
