### ISSUE TITLE
Error in the AREPL extension! Error running python with command: 

### ISSUE THREAD

**Issue by hkd8** [Almenon/AREPL-vscode#170] opened 2019-01-31 23:28 UTC
![error arepl](https://user-images.githubusercontent.com/46432203/52092564-8be9b600-257d-11e9-873c-be610a86e131.png)

**Comment by hkd8** [comment] 2019-02-01 03:57
Python is installed. Version 3.7.1.

Have checked environment paths, all seem to be set accordingly.

**Comment by Almenon** [comment] 2019-02-01 04:18
odd..... python 3.3+ should create a file called "py.exe" in the C:\Windows directory. Can you check if it's there please? Where did you install python from?

**Comment by hkd8** [comment] 2019-02-01 05:19
Not seeing a py.exe file in that folder. I do have python.exe in the
general anaconda folder in a different location. Is that the issue?

Downloaded python off the official website.

Fairly new to programming so I may have some missteps or not know the
proper locations, appreciate the help.

**Comment by Almenon** [comment] 2019-02-01 08:07
The issue is that your py.exe is Missing.  I assumed that py.exe would always be present but looks like that is not the case .....  :/ In the future I plan to switch arepl python path to default to python extension's python path, so if that works then arepl will work

**Comment by Almenon** [comment] 2019-02-01 08:08
In the meantime I suggest just changing the arepl pythonpath to simply python

**Comment by Almenon** [comment] 2019-02-01 08:08
If you can launch python in the command line by typing python then this should work

**Comment by aurelion314** [comment] 2019-02-04 00:47
py.exe is a shortcut that can optionally be installed with python. Not all installs will have it. Can you update the extension run the the full 'python' command instead? 

I don't have a py.exe either and this is the first extension that isn't working because of it. It looks like a great extension and I'm tempted to re-install python with py.exe, but its a hassle that could easily be avoided.

**Comment by Almenon** [comment] 2019-02-05 02:19
You don't have to reinstall python, you just need to change the arepl.pythonpath setting to "python".

I originally had 'python' as the default but @jamesgeorge007 reccomended that I switch it to 'py'.  I was unaware that 'py' is not always availible.

Like I said before I'm planning on switching the default python path to use the python extension's path, because presumably people will have already configured that to work.  The python extension uses 'python' as a default.  Do you have the python extension installed?

**Comment by Almenon** [comment] 2019-02-06 06:08
Closing - I'm going to release tonight with the change I mentioned to the python path. If you have the python extension installed arepl will use that path instead, which should be better for everyone.

**Closed by Almenon** 2019-02-06 06:08 UTC
Labels: bug, spawning

**Comment by Almenon** [comment] 2019-02-06 06:33
Just released a new version of arepl. @aurelion314 @hkd8 is it working for you now?

**Comment by aurelion314** [comment] 2019-02-07 03:02
It almost works!

The first time I tried after the update it worked great! However I killed the script accidentally (with an exit()) and now anytime I try to restart AREPL it shows the start view telling me to try making a change, but when I do, it throws an error similar to before:
"'py' is not recognized as an internal or external command,
operable program or batch file."

Looks like its reverting to 'py' under different circumstance?

**Comment by Almenon** [comment] 2019-02-07 04:22
@aurelion314 That's very strange. If you go to your settings what value do you have for python.pythonPath? Is it the same for user, workspace, and folder?  What about arepl.pythonpath?

**Comment by aurelion314** [comment] 2019-02-07 16:55
@Almenon arepl.pythonpath was null. If I change it to python, same thing happens. It loads initially and tells me to try changing something, but when I do it throws the py error.

If I change pythonpath to something completely wrong, it does not even load the initial welcome screen.  Makes me think this path is correct, thus loading initially, but there is some later call that ignores it and assumes 'py'? Yet strangely never got called the first time I ran AREPL.. :\

**Comment by Almenon** [comment] 2019-02-08 03:57
@aurelion314 I have no clue why that's happening, is it okay if you try my debug version of arepl? You can install it by going to extensions and clicking on three horizontal dots on the top clicking install from vsix, and then choosing the file you downloaded from the link below. 

It will log a bunch of debug info to the dev console -  you can view the output by clicking on help and then toggle developer tools. If you paste it here hopefully I'll have a better idea of what's going on.

https://github.com/Almenon/AREPL-vscode/releases/tag/debug

**Comment by hkd8** [comment] 2019-02-10 21:24
> @aurelion314 I have no clue why that's happening, is it okay if you try my debug version of arepl? You can install it by going to extensions and clicking on three horizontal dots on the top clicking install from vsix, and then choosing the file you downloaded from the link below.
> It will log a bunch of debug info to the dev console -  you can view the output by clicking on help and then toggle developer tools. If you paste it here hopefully I'll have a better idea of what's going on.
> https://github.com/Almenon/AREPL-vscode/releases/tag/debug

[Extension Host] Here is the error stack:  Error: Command failed: C:\Users\cheng\AppData\Local\Programs\Microsoft VS Code -m site --user-site
'C:\Users\cheng\AppData\Local\Programs\Microsoft' is not recognized as an internal or external command,
operable program or batch file.

	at checkExecSyncError (child_process.js:615:11)
	at Object.execSync (child_process.js:652:13)
	at Object.execSync (ELECTRON_ASAR.js:746:23)
	at getsitePackagePath (C:\Users\cheng\.vscode\extensions\almenon.arepl-1.0.8\out\src\registerAreplDump.js:31:28)
	at Object.registerAreplDump (C:\Users\cheng\.vscode\extensions\almenon.arepl-1.0.8\out\src\registerAreplDump.js:12:29)
	at activate (C:\Users\cheng\.vscode\extensions\almenon.arepl-1.0.8\out\src\extension.js:32:25)
	at Function.t._callActivateOptional (c:\Users\cheng\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:741:354)
	at Function.t._callActivate (c:\Users\cheng\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:741:25)
	at c:\Users\cheng\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:740:206
console.ts:134 [Extension Host] starting arepl
console.ts:134 [Extension Host] arepl path is C:\Users\cheng\AppData\Local\Programs\Microsoft VS Code
console.ts:134 [Extension Host] python ext is installed
console.ts:134 [Extension Host] pythonext python path is python
console.ts:134 [Extension Host] after replacing pythonPath with pythonExtPythonPath, pythonPath now is C:\Users\cheng\AppData\Local\Programs\Microsoft VS Code
console.ts:134 [Extension Host] pythonpath after replacing ${workspaceFolder} macro: C:\Users\cheng\AppData\Local\Programs\Microsoft VS Code
console.ts:134 [Extension Host] pythonpath after replacing ${python.pythonPath} macro: C:\Users\cheng\AppData\Local\Programs\Microsoft VS Code
console.ts:134 [Extension Host] returning C:\Users\cheng\AppData\Local\Programs\Microsoft VS Code
console.ts:134 [Extension Host] passing C:\Users\cheng\AppData\Local\Programs\Microsoft VS Code into backend
console.ts:134 [Extension Host] Starting Python...

**Comment by Almenon** [comment] 2019-02-10 21:49
@hkd8 that means in your settings you have arepl.pythonpath set to C:\Users\cheng\AppData\Local\Programs\Microsoft VS Code.  If you look in your settings what is arepl.pythonpath set to?  It should be empty for user, workspace, and folder

**Comment by Almenon** [comment] 2019-02-10 21:58
sorry should have mentioned that earlier, it was right there in your picture, not sure how I didnt notice it

**Comment by hkd8** [comment] 2019-02-10 22:06
that seemed to be my problem! Thanks for the help, everything seems to be working now!

**Comment by aurelion314** [comment] 2019-02-10 22:12
I tried it again and seems to be working! Weird that it was failing last time, maybe a full reboot was needed to reset something. Anyway thanks for the fix!
