### ISSUE TITLE
Arepl not refreshing

### ISSUE THREAD

**Issue by ajay611** [Almenon/AREPL-vscode#367] opened 2020-11-25 11:28 UTC
trying to configure arepl. Wrote a small piece of code but arepl is not showing all the variables and not refreshing.
![image](https://user-images.githubusercontent.com/48642492/100221978-5a3f9d00-2f11-11eb-9379-436a405dea6a.png)

**Comment by Almenon** [comment] 2020-11-26 04:33
I tried typing your code out with a SyntaxError and when I fixed the SyntaxError it worked. How often does this problem happen?

https://i.imgur.com/Gpdi5ft.png

**Comment by Almenon** [comment] 2021-02-14 01:57
Following up on this

**Comment by ostap-tymchenko** [comment] 2021-04-18 21:05
same thing here. worked fine for a while. reinstalling does not help.
![image](https://user-images.githubusercontent.com/56374185/115160818-40d9f180-a068-11eb-8d9d-854d7305b3ae.png)

**Comment by Almenon** [comment] 2021-04-19 00:05
What's the value of python.pythonpath and arepl.pythonpath settings?

**Comment by ostap-tymchenko** [comment] 2021-04-19 03:04
> What's the value of python.pythonpath and arepl.pythonpath settings?

where can I find those tags?

**Comment by ostap-tymchenko** [comment] 2021-04-19 03:08
its empty, should i set it to somthing? ps this at least for me wasn't changed wh

**Comment by ostap-tymchenko** [comment] 2021-04-19 03:24
here is a simpler example. 
![image](https://user-images.githubusercontent.com/56374185/115177414-2e2ddf80-a09d-11eb-997c-b51e6ece5aca.png)

**Comment by ostap-tymchenko** [comment] 2021-04-19 03:24
and here are my extentions 
![image](https://user-images.githubusercontent.com/56374185/115177438-3ede5580-a09d-11eb-92aa-979b90246ceb.png)

**Comment by ostap-tymchenko** [comment] 2021-04-19 03:26
> here is a simpler example.
> ![image](https://user-images.githubusercontent.com/56374185/115177414-2e2ddf80-a09d-11eb-997c-b51e6ece5aca.png)

and even after restart the error is the same.

**Comment by Almenon** [comment] 2021-04-19 04:23
You can find those settings by going to the settings page and searching for them in the search bar:

https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings

**Comment by Almenon** [comment] 2021-04-19 04:24
Oh wait you already got the values, nevermind.

**Comment by Almenon** [comment] 2021-04-19 04:25
What os are you using? Are you able to run `python` from the terminal?

**Comment by ostap-tymchenko** [comment] 2021-04-19 04:51
Windows 10, python works just fine everywhere, bash cmd and vscode. I can't find anything wrong and arepl worked just fine for a long time. All my arepl settings are set to default btw.

**Comment by ostap-tymchenko** [comment] 2021-04-19 11:29
can we change the issue to just arepl not refreshing? variables not all showing up is just the same issue in a different context.

**Comment by Almenon** [comment] 2021-04-21 15:28
Can you go to help -> toggle developer tools, open arepl, and then send me the console output please?

**Comment by ostap-tymchenko** [comment] 2021-04-21 15:47
it just kept saying "python starting"! 
![image](https://user-images.githubusercontent.com/56374185/115582821-508b4d00-a297-11eb-8517-f570995a8322.png)
I left it alone for a couple minutes and it never ended up doing anythign

**Comment by Almenon** [comment] 2021-04-22 15:43
Weird - are you free sometime for a quick zoom/discord call? If I see it in person I might be able to figure it out. I'm busy 9-5 pacific time for work but usually free besides then.

**Comment by ostap-tymchenko** [comment] 2021-04-22 17:58
yep sure, how about 6 pm pacific then? although it's fine if it's later than that I am est so I would appreciate not pushing it back further than that because that's already 9 pm for me. or if you would like tomorrow then ill be up at around 6 am pacific. i prefer discord but zoom is fine too. lemongras#7245 also I've been messing around with it more and it seems to only be happening in certain specific code instances, not globally. not sure if that's a good or bad thing. I'm working on figuring it out right now.

**Comment by ostap-tymchenko** [comment] 2021-04-22 18:02
update: ive narrowed it down, file opening and for loops  (together)
![image](https://user-images.githubusercontent.com/56374185/115764253-55bdca00-a373-11eb-88c6-7da5deb1df08.png)

**Comment by ostap-tymchenko** [comment] 2021-04-22 18:03
heres a simpler version
![image](https://user-images.githubusercontent.com/56374185/115764445-8ef63a00-a373-11eb-9ed2-0088b54041f8.png)

**Comment by Almenon** [comment] 2021-04-23 02:31
oh, the issue is because you have a infinite loop. Try saving the below to a file named "a.py" and executing it on the command line with "python a.py". It will never stop.

```python
while True:
  pass
```

AREPL gets results once the program finishes, so if the program never finishes AREPL can't display results.

**Comment by ostap-tymchenko** [comment] 2021-04-23 17:28
shouldn't there be an exception for a while True: pass then? it stopes the entire file so if there's nothing in the loop it should probably ignore it/start another instance.

**Comment by Almenon** [comment] 2021-04-24 04:16
Python only throws an exception when there is a invalid operation, a Exception thrown intentionally, or invalid syntax. `while True: pass` is technically a valid operation. You're telling python to do nothing when True is True, and True is always True, so python does nothing.

**Comment by ostap-tymchenko** [comment] 2021-04-24 21:20
then can we do anything to stop it from upending the entirety of arepl? if a user wants to know whats going on and has to write that and for some reason keep it for a bit they cant use arepl whatsoever.

**Comment by Almenon** [comment] 2021-04-25 17:41
While loops should generally have a statement that breaks out of the loop. For example:

```python
i = 0
while i < 10:
  print(i)
  i = i+1

```

print output:
0
1
2
3
4
5
6
7
8
9
\<end\>

**Comment by ostap-tymchenko** [comment] 2021-04-25 23:49
well the thing is if you realize your mistake and change the loop from a while to a for loop you still have to restart arepl.

**Comment by Almenon** [comment] 2022-05-14 21:31
> well the thing is if you realize your mistake and change the loop from a while to a for loop you still have to restart arepl.

Yep, you have to restart AREPL. It's a bit inconvenient, I admit, but it doesn't take that long.

Unfortunately it's very hard to determine whether the code is in a infinite loop or not. A true solution to the issue is literally impossible - see [the halting problem](https://en.wikipedia.org/wiki/Halting_problem). Best I could do is workarounds to the problem at hand.

There is a [old issue](https://github.com/Almenon/AREPL-vscode/issues/122) for adding a restart shortcut, so you could manually restart in cases like these. Would this be useful to you? Would you prefer a button or shortcut?

**Comment by goyalyashpal** [comment] 2023-04-13 12:16
i remember seeing somewhere there was mentioned that arepl requires editing code, etc... and you said that yeah, u want user to know what file they are in, and you need some place to share info about arepl and will add more stuff to it...

**Comment by Almenon** [comment] 2024-11-19 06:36
This should be fixed if you upgrade to AREPL v3 :)

Now if there's a infinite loop you can edit your code to fix the loop and AREPL will start working again without needing to be restarted.

**Closed by Almenon** 2024-11-19 06:36 UTC
